apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: db-b
  labels:
    app: mariadb
    instance: db-b
spec:
  selector:
    app: mariadb
    instance: db-b
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    - name: metrics
      port: 9104
      targetPort: 9104
  type: ClusterIP
