apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
  namespace: {{ .Values.instance }}
  labels:
    app: mariadb
    instance: {{ .Values.instance }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.exporterUser | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.exporterPassword | quote }}
  MYSQLD_EXPORTER_DSN: "{{ .Values.mariadb.exporterUser }}:{{ .Values.mariadb.exporterPassword }}@tcp(127.0.0.1:3306)/"
