apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Values.instance }}
  labels:
    app: mariadb
    instance: {{ .Values.instance }}
spec:
  selector:
    app: mariadb
    instance: {{ .Values.instance }}
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
    - name: metrics
      port: 9104
      targetPort: metrics
