apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: db-a
data:
  custom.cnf: |
    [mysqld]
    character-set-server  = utf8mb4
    collation-server      = utf8mb4_unicode_ci
    max_connections       = 100
    innodb_buffer_pool_size = 128M
    innodb_log_file_size    = 32M
    innodb_flush_log_at_trx_commit = 2
    slow_query_log        = 1
    slow_query_log_file   = /tmp/slow.log
    long_query_time       = 1

    [client]
    default-character-set  = utf8mb4
