apiVersion: v1
kind: Namespace
metadata:
  name: db-a
  labels:
    purpose: database
    instance: db-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: db-b
  labels:
    purpose: database
    instance: db-b
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    purpose: monitoring
